print("")
print("#     #     ooooo      #        #           ooooo")
print("#     #    o     o     #        #          o     o")
print("#######   o ======o    #        #         o       o")
print("#     #   o            #        #         o       o")
print("#     #    o           #        #          o     o")
print("#     #     oooooo     ######   ######      ooooo")

while True :
        try:
                print("")
                type65 = (str(input("vrsion type (+ - * / ^ )(e to Exit) >_ ")))
                if type65 == "e":
                        break
                # / --> (+),(-),(*),(/)
                # = (+)
                if  type65 == "+":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))
                        print ("")
                        print(a,type65,b,"=",a+b)
                # = (-)
                elif type65 == "-":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))    
                        print ("")
                        print(a,type65,b,"=",a-b)
                # = (*)
                elif type65 == "*":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))  
                        print ("")
                        print(a,type65,b,"=",a*b)
                # = (/)
                elif type65 == "/":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))
                        print("")
                        if b == 0 :
                                print ("Error numer 2 =",b)
                                print ("                ^")
                        else:
                                print (a,type65,b,"=",a/b)   
                # = (^ or **)                        
                elif type65 == "^":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))
                        print ("")
                        print (a,type65,b,"=",a**b)
                # = (%)                 
                elif type65 == "%":
                        a=float(input("numer 1 = "))
                        b=float(input("numer 2 = "))
                        print ("")
                        print (a,type65,b,"=",a%b)
        except TypeError:
                print ("        # ")                    
                print ("       # # ")
                print ("      # | # ")
                print ("     #  |  # ")
                print ("    #   |   # ")
                print ("   #    |    # ")
                print ("  #     |     # ")
                print (" #      O      # ")
                print("#---------------# ")
                print("     TypeError        ")
        except ValueError:
                print ("        # ")                    
                print ("       # # ")
                print ("      # | # ")
                print ("     #  |  # ")
                print ("    #   |   # ")
                print ("   #    |    # ")
                print ("  #     |     # ")
                print (" #      O      # ")
                print("#---------------# ")
                print("    ValueError     ")                             
        except OverflowError:
                print ("        # ")                    
                print ("       # # ")
                print ("      # | # ")
                print ("     #  |  # ")
                print ("    #   |   # ")
                print ("   #    |    # ")
                print ("  #     |     # ")
                print (" #      O      # ")
                print("#---------------# ")
                print("  OverflowError")

print("")
print("  ooooo       ooooo       ooooo     ======o          ##     #     #")
print(" o           o     o     o     o    |      o        #  #     #   #")
print("o           o       o   o       o   |==== o        #   #      # #")
print("o       O   o       o   o       o   |==== o       ######       #")
print(" o      O    o     o     o     o    |      o     #     #       #")
print("  oooooo      ooooo       ooooo     ======o     #      #       #")
print("")